"""
subscriberHD.py

User 2 - Predictive Maintenance Monitoring Client

functions:
- subscribes to machine telemetry
- performs threshold-based predictive maintenance analysis
- publishes machine condition predictions
- generates maintenance and operational commands
"""

import json # for handling JSON data in MQTT messages
import paho.mqtt.client as mqtt # for MQTT communication between publisher and subscriber

# MQTT broker configuration
broker = "localhost" # use 192.168.12.100 as local broker IP
port = 1883
# student_id and machine_id are used to construct MQTT topics for both publisher and subscriber
student_id = "102781776"
machine_id = "machine01"

# MQTT topics
public_topic1 = f"public/102781776/machine01/sensors"
public_topic2 = f"public/102781776/machine01/prediction"
command_topic = f"public/102781776/machine01/command"
status_topic = f"102781776/status/user2" # for debugging purposes

# Prediction logic to analyze machine state based on temperature and vibration readings
# OBJ 1: Automatically generate prediction messages based on Topic 1 and publish to Topic 2
# This function analyses incoming temperature and vibration readings received from Topic 1: public/102781776/machine01/sensors
# It generates a prediction result: NORMAL, WARNING or CRITICAL.
def analyse_machine(temperature, vibration):
    # critical condition if temperature is 85 or above, or vibration is 6 or above
    if temperature >= 85 or vibration >= 6:
        return {
            "condition": "CRITICAL",
            "risk_score": 90,
            "recommended_action": "STOP_MACHINE_AND_INSPECT",
            "reason": "Temperature or vibration is too high"
        }
    # warning condition if temperature is 75 or above, or vibration is 4.5 or above
    elif temperature >= 75 or vibration >= 4.5:
        return {
            "condition": "WARNING",
            "risk_score": 60,
            "recommended_action": "ENABLE_COOLING_AND_SCHEDULE_MAINTENANCE",
            "reason": "Temperature or vibration is above normal range"
        }
    # normal condition if temperature is below 75 and vibration is below 4.5
    else:
        return {
            "condition": "NORMAL",
            "risk_score": 15,
            "recommended_action": "CONTINUE_OPERATION",
            "reason": "Machine is operating normally"
        }

# on_connect callback function to handle connection events
# client: MQTT client instance
# userdata: user-defined data
# flags: contains response flags from the broker
# rc: connection result code
def on_connect(client, userdata, flags, rc):
    if rc == 0:
        print("User 2 connected to MQTT broker")
        # OBJ 2: User 2 subscribes to Topic 1 to receive and display sensor readings generated by User 1.
        # Topic 1: public/102781776/machine01/sensors
        client.subscribe(public_topic1)
        print("Subscribed to:", public_topic1)

        client.publish(
            status_topic,
            json.dumps({"user": "User 2", "status": "online"}, indent=4),
            retain=True
        )
    else:
        print("Connection failed with code:", rc)

# on_message callback function to receive messages from Topic 1, displays the payload,
# analyses the machine condition, then publishes the generated prediction message to Topic 2
def on_message(client, userdata, message):
    # decodes the incoming message payload from bytes to string
    payload_text = message.payload.decode()

    print("\nUser 2 received message")
    print("Topic:", message.topic)
    print("Payload:")
    print(payload_text)

    if message.topic != public_topic1:
        return
    # processes messages from the sensor topic, extracts temperature and vibration data, generates analysis and predictions, and 
    # publishes results to the prediction topic and command topic if necessary
    try:
        payload = json.loads(payload_text)

        temperature = float(payload["temperature_c"])
        vibration = float(payload["vibration_mm_s"])

        # OBJ 1.1: analyses the machine condition based on the received sensor data (Topic 1) and 
        # generates a prediction payload
        analysis = analyse_machine(temperature, vibration)

        prediction_payload = {
            "machine_id": machine_id,
            "temperature_c": temperature,
            "vibration_mm_s": vibration,
            "condition": analysis["condition"],
            "risk_score": analysis["risk_score"],
            "recommended_action": analysis["recommended_action"],
            "reason": analysis["reason"]
        }

        # publishes the prediction result to Topic 2: public/102781776/machine01/prediction for User 1 to receive and act upon
        client.publish(
            public_topic2,
            json.dumps(prediction_payload, indent=4)
        )

        print("\nUser 2 published prediction to:")
        print(public_topic2)
        print(json.dumps(prediction_payload, indent=4))

        # extra functionality: auto command generation
        # If the prediction is WARNING or CRITICAL, User 2 publishes a command to the command topic.
        # complements the system by adding automatic cooling or emergency response behaviour.
        if analysis["condition"] == "WARNING" or analysis["condition"] == "CRITICAL":
            # constructs command payload with machine ID, recommended action, and reason for the command based on the analysis
            command_payload = {
                "machine_id": machine_id,
                "command": analysis["recommended_action"],
                "reason": analysis["reason"]
            }

            client.publish(
                command_topic,
                json.dumps(command_payload, indent=4)
            )

            print("\nUser 2 published command to:")
            print(command_topic)
            print(json.dumps(command_payload, indent=4))
    # handles any exceptions that occur during message processing and prints an error message
    except Exception as error:
        print("Error processing message:", error)

# MQTT Client setup to connect to the broker, subscribe to topics, and handle incoming messages with defined callback functions
client = mqtt.Client()
username = "102781776"
password = "102781776"

client.username_pw_set(username, password)
client.will_set(
    status_topic,
    json.dumps({"user": "User 2", "status": "offline unexpectedly"}, indent=4),
    retain=True
)

# on_connect and on_message callback functions are assigned to the client to handle connection and message events
# allowing the subscriber to react to incoming messages and connection status changes
client.on_connect = on_connect
client.on_message = on_message

client.connect(broker, port, 60)

# main loop to keep the subscriber running and handle incoming messages until interrupted, 
# at which point it will publish an offline status update and disconnect from the broker
try:
    client.loop_forever()

except KeyboardInterrupt:
    print("\nUser 2 disconnecting...")

    client.publish(
        status_topic,
        json.dumps({"user": "User 2", "status": "offline"}, indent=4),
        retain=True
    )

    client.disconnect()